const glyphs = {

    "happy": require('../svgs/happy.svg'),
    "sad": require('../svgs/sad.svg'),

    "twitter": require('../svgs/twitter.svg'),
    "instagram": require('../svgs/instagram.svg'),
    "vine": require('../svgs/vine.svg'),
    "facebook": require('../svgs/facebook.svg'),
    "youtube": require('../svgs/youtube.svg'),

    "kr": require('../svgs/kr.svg'),
    "ca": require('../svgs/ca.svg'),
    "us": require('../svgs/us.svg'),
    "gb": require('../svgs/gb.svg'),
    "au": require('../svgs/au.svg'),
    "de": require('../svgs/de.svg'),
    "fr": require('../svgs/fr.svg'),
    "pl": require('../svgs/pl.svg'),
    "it": require('../svgs/it.svg'),
    "es": require('../svgs/es.svg'),
    "nl": require('../svgs/nl.svg'),
    "ru": require('../svgs/ru.svg'),
    "cn": require('../svgs/cn.svg'),
    "ch": require('../svgs/ch.svg'),

    "launchpad": require('../svgs/launchpad.svg'),
    "code": require('../svgs/code.svg'),
    "chart": require('../svgs/data.svg'),
    "eyedropper": require('../svgs/design.svg'),
    "notification": require('../svgs/notification.svg'),
    "settings": require('../svgs/settings.svg'),
    "search": require('../svgs/search.svg'),
    "splash": require('../svgs/splash.svg'),
    "hamburger": require('../svgs/hamburger.svg'),
    // go find chevrons and then remove this
    // "arrow-right": require('../svgs/chevron-right.svg'),
    // new class for chevron
    "chevron-right": require('../svgs/chevron-right.svg'),
    "chevron-left": require('../svgs/chevron-left.svg'),
    "export": require('../svgs/export.svg'),

    // builder ui icons
    "arrow-left": require('../svgs/arrow-left.svg'),
    "arrow-right": require('../svgs/arrow-right.svg'),
    "minus": require('../svgs/minus.svg'),
    "minus-alt": require('../svgs/minus-alt.svg'),
    "plus": require('../svgs/plus.svg'),
    "plus-alt": require('../svgs/plus-alt.svg'),
    "check": require('../svgs/check.svg'),
    "check-alt": require('../svgs/check-alt.svg'),
    "bell": require('../svgs/bell.svg'),
    "calendar": require('../svgs/calendar.svg'),
    "camera": require('../svgs/camera.svg'),
    "clock": require('../svgs/clock.svg'),
    "cog": require('../svgs/cog.svg'),
    "filter": require('../svgs/filter.svg'),
    "frown": require('../svgs/frown.svg'),
    "key": require('../svgs/key.svg'),
    "lock": require('../svgs/lock.svg'),
    "movie": require('../svgs/movie.svg'),
    "pen": require('../svgs/pen.svg'),
    "pin": require('../svgs/pin.svg'),
    "search2": require('../svgs/search2.svg'),
    "share": require('../svgs/share.svg'),
    "smile": require('../svgs/smile.svg'),
    "star": require('../svgs/star.svg'),
    "tag": require('../svgs/tag.svg'),
    "unlock": require('../svgs/unlock.svg'),
    "user": require('../svgs/user.svg'),
    "wondering": require('../svgs/wondering.svg'),

    "bars": require('../svgs/bars.svg'),
    "bars-alt": require('../svgs/bars-alt.svg'),
    "equalizer": require('../svgs/equalizer.svg'),
    "grid": require('../svgs/grid.svg'),
    "image": require('../svgs/image.svg'),
    "x": require('../svgs/x.svg'),
    "x-alt": require('../svgs/x-alt.svg'),
    "animation": require('../svgs/animation.svg'),
    "order": require('../svgs/order.svg'),
    "time": require('../svgs/time.svg'),
    "trash": require('../svgs/trash.svg'),
    "growth": require('../svgs/growth.svg'),

    "mc-content": require('../svgs/mc-content.svg'),
    "mc-growth": require('../svgs/mc-growth.svg'),
    "mc-reaction": require('../svgs/mc-reaction.svg')

}

export default glyphs;
